// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/schema/goal_store_data.dart';
import 'core/schema/key_value_store_data.dart';
import 'core/schema/person_store_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9091616633448040374),
    name: 'KeyValueStoreData',
    lastPropertyId: const obx_int.IdUid(6, 1267079675268533712),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6968941250967527322),
        name: 'keyId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 971535068884585735),
        name: 'keyName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4109068427320318735),
        name: 'value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4701697490493537585),
        name: 'defaultValue',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6002816074833289441),
    name: 'PersonStoreData',
    lastPropertyId: const obx_int.IdUid(4, 6523744231814229197),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5794725333635122836),
        name: 'personId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6008990428660585266),
        name: 'personName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 763221525240517549),
        name: 'age',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6523744231814229197),
        name: 'personEmail',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2912203013853609161),
    name: 'GoalStoreData',
    lastPropertyId: const obx_int.IdUid(6, 2305601635046110762),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2330223296124703673),
        name: 'goalId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6250277381479515238),
        name: 'goalName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3557137753056099793),
        name: 'goalType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6834458189301563533),
        name: 'startDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5801628919320258526),
        name: 'endDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2305601635046110762),
        name: 'targetAmount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 2912203013853609161),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [8794158497278557681],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7674852691405824369,
      1267079675268533712,
      4143108571151452684,
      3453169864485762507,
      2207615828984540389,
      3744185936353417413,
      4403983905597986307,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    KeyValueStoreData: obx_int.EntityDefinition<KeyValueStoreData>(
      model: _entities[0],
      toOneRelations: (KeyValueStoreData object) => [],
      toManyRelations: (KeyValueStoreData object) => {},
      getId: (KeyValueStoreData object) => object.keyId,
      setId: (KeyValueStoreData object, int id) {
        object.keyId = id;
      },
      objectToFB: (KeyValueStoreData object, fb.Builder fbb) {
        final keyNameOffset = fbb.writeString(object.keyName);
        final valueOffset = fbb.writeString(object.value);
        final defaultValueOffset = object.defaultValue == null
            ? null
            : fbb.writeString(object.defaultValue!);
        fbb.startTable(7);
        fbb.addInt64(0, object.keyId);
        fbb.addOffset(1, keyNameOffset);
        fbb.addOffset(2, valueOffset);
        fbb.addOffset(4, defaultValueOffset);
        fbb.finish(fbb.endTable());
        return object.keyId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final keyIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final defaultValueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = KeyValueStoreData(
          keyId: keyIdParam,
          keyName: keyNameParam,
          value: valueParam,
          defaultValue: defaultValueParam,
        );

        return object;
      },
    ),
    PersonStoreData: obx_int.EntityDefinition<PersonStoreData>(
      model: _entities[1],
      toOneRelations: (PersonStoreData object) => [],
      toManyRelations: (PersonStoreData object) => {},
      getId: (PersonStoreData object) => object.personId,
      setId: (PersonStoreData object, int id) {
        object.personId = id;
      },
      objectToFB: (PersonStoreData object, fb.Builder fbb) {
        final personNameOffset = fbb.writeString(object.personName);
        final personEmailOffset = fbb.writeString(object.personEmail);
        fbb.startTable(5);
        fbb.addInt64(0, object.personId);
        fbb.addOffset(1, personNameOffset);
        fbb.addInt64(2, object.age);
        fbb.addOffset(3, personEmailOffset);
        fbb.finish(fbb.endTable());
        return object.personId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final personIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final personNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final ageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final personEmailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = PersonStoreData(
          personId: personIdParam,
          personName: personNameParam,
          age: ageParam,
          personEmail: personEmailParam,
        );

        return object;
      },
    ),
    GoalStoreData: obx_int.EntityDefinition<GoalStoreData>(
      model: _entities[2],
      toOneRelations: (GoalStoreData object) => [],
      toManyRelations: (GoalStoreData object) => {},
      getId: (GoalStoreData object) => object.goalId,
      setId: (GoalStoreData object, int id) {
        object.goalId = id;
      },
      objectToFB: (GoalStoreData object, fb.Builder fbb) {
        final goalNameOffset = fbb.writeString(object.goalName);
        final goalTypeOffset = fbb.writeString(object.goalType);
        final startDateOffset = fbb.writeString(object.startDate);
        final endDateOffset = fbb.writeString(object.endDate);
        fbb.startTable(7);
        fbb.addInt64(0, object.goalId);
        fbb.addOffset(1, goalNameOffset);
        fbb.addOffset(2, goalTypeOffset);
        fbb.addOffset(3, startDateOffset);
        fbb.addOffset(4, endDateOffset);
        fbb.addInt64(5, object.targetAmount);
        fbb.finish(fbb.endTable());
        return object.goalId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final goalIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final goalNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final goalTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final endDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final targetAmountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = GoalStoreData(
          goalId: goalIdParam,
          goalName: goalNameParam,
          goalType: goalTypeParam,
          startDate: startDateParam,
          endDate: endDateParam,
          targetAmount: targetAmountParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [KeyValueStoreData] entity fields to define ObjectBox queries.
class KeyValueStoreData_ {
  /// See [KeyValueStoreData.keyId].
  static final keyId = obx.QueryIntegerProperty<KeyValueStoreData>(
    _entities[0].properties[0],
  );

  /// See [KeyValueStoreData.keyName].
  static final keyName = obx.QueryStringProperty<KeyValueStoreData>(
    _entities[0].properties[1],
  );

  /// See [KeyValueStoreData.value].
  static final value = obx.QueryStringProperty<KeyValueStoreData>(
    _entities[0].properties[2],
  );

  /// See [KeyValueStoreData.defaultValue].
  static final defaultValue = obx.QueryStringProperty<KeyValueStoreData>(
    _entities[0].properties[3],
  );
}

/// [PersonStoreData] entity fields to define ObjectBox queries.
class PersonStoreData_ {
  /// See [PersonStoreData.personId].
  static final personId = obx.QueryIntegerProperty<PersonStoreData>(
    _entities[1].properties[0],
  );

  /// See [PersonStoreData.personName].
  static final personName = obx.QueryStringProperty<PersonStoreData>(
    _entities[1].properties[1],
  );

  /// See [PersonStoreData.age].
  static final age = obx.QueryIntegerProperty<PersonStoreData>(
    _entities[1].properties[2],
  );

  /// See [PersonStoreData.personEmail].
  static final personEmail = obx.QueryStringProperty<PersonStoreData>(
    _entities[1].properties[3],
  );
}

/// [GoalStoreData] entity fields to define ObjectBox queries.
class GoalStoreData_ {
  /// See [GoalStoreData.goalId].
  static final goalId = obx.QueryIntegerProperty<GoalStoreData>(
    _entities[2].properties[0],
  );

  /// See [GoalStoreData.goalName].
  static final goalName = obx.QueryStringProperty<GoalStoreData>(
    _entities[2].properties[1],
  );

  /// See [GoalStoreData.goalType].
  static final goalType = obx.QueryStringProperty<GoalStoreData>(
    _entities[2].properties[2],
  );

  /// See [GoalStoreData.startDate].
  static final startDate = obx.QueryStringProperty<GoalStoreData>(
    _entities[2].properties[3],
  );

  /// See [GoalStoreData.endDate].
  static final endDate = obx.QueryStringProperty<GoalStoreData>(
    _entities[2].properties[4],
  );

  /// See [GoalStoreData.targetAmount].
  static final targetAmount = obx.QueryIntegerProperty<GoalStoreData>(
    _entities[2].properties[5],
  );
}
