// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/schema/key_value_store_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9091616633448040374),
    name: 'KeyValueStoreData',
    lastPropertyId: const obx_int.IdUid(6, 1267079675268533712),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6968941250967527322),
        name: 'keyId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 971535068884585735),
        name: 'keyName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4109068427320318735),
        name: 'value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4701697490493537585),
        name: 'defaultValue',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 9091616633448040374),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [7674852691405824369, 1267079675268533712],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    KeyValueStoreData: obx_int.EntityDefinition<KeyValueStoreData>(
      model: _entities[0],
      toOneRelations: (KeyValueStoreData object) => [],
      toManyRelations: (KeyValueStoreData object) => {},
      getId: (KeyValueStoreData object) => object.keyId,
      setId: (KeyValueStoreData object, int id) {
        object.keyId = id;
      },
      objectToFB: (KeyValueStoreData object, fb.Builder fbb) {
        final keyNameOffset = fbb.writeString(object.keyName);
        final valueOffset = fbb.writeString(object.value);
        final defaultValueOffset = object.defaultValue == null
            ? null
            : fbb.writeString(object.defaultValue!);
        fbb.startTable(7);
        fbb.addInt64(0, object.keyId);
        fbb.addOffset(1, keyNameOffset);
        fbb.addOffset(2, valueOffset);
        fbb.addOffset(4, defaultValueOffset);
        fbb.finish(fbb.endTable());
        return object.keyId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final keyIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final defaultValueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = KeyValueStoreData(
          keyId: keyIdParam,
          keyName: keyNameParam,
          value: valueParam,
          defaultValue: defaultValueParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [KeyValueStoreData] entity fields to define ObjectBox queries.
class KeyValueStoreData_ {
  /// See [KeyValueStoreData.keyId].
  static final keyId = obx.QueryIntegerProperty<KeyValueStoreData>(
    _entities[0].properties[0],
  );

  /// See [KeyValueStoreData.keyName].
  static final keyName = obx.QueryStringProperty<KeyValueStoreData>(
    _entities[0].properties[1],
  );

  /// See [KeyValueStoreData.value].
  static final value = obx.QueryStringProperty<KeyValueStoreData>(
    _entities[0].properties[2],
  );

  /// See [KeyValueStoreData.defaultValue].
  static final defaultValue = obx.QueryStringProperty<KeyValueStoreData>(
    _entities[0].properties[3],
  );
}
